### ISSUE TITLE
Ce n'est pas très organisé ici...

### ISSUE THREAD

**Issue by dotether** [NaisHoang/Fuzzy-Train#2]
**Le Gange est un fleuve de la plaine indo-gangétique, au nord de l'Inde. Sa longueur varie suivant les sources de 2 500 à 3 000 km, son bassin couvre 907 000 km² et son delta est commun avec celui du Brahmapoutre. Le Gange est la plus sainte des sept rivières sacrées de l'Inde**

**Comment by Leolfg** [comment]
Merci d'ajouter un point à la fin de votre proposition.

**Comment by dotether** [comment]
parle meilleur toi

**Comment by dotether** [comment]
@lecapitaine237 cc

**Comment by Leolfg** [comment]
Inutile ! Je ferme l'issue. xoxo

**Comment by dotether** [comment]
:(
